global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'gadukagang_django'
    metrics_path: /metrics
    static_configs:
      - targets: ['frontend:8000']
        labels:
          service: 'gadukagang-web'

